### ISSUE TITLE
Hammertime needs node6 (I think)

### ISSUE THREAD

**Issue by exidy** [nib-health-funds/hammertime#12]
`serverless.yml` specifies `runtime: nodejs4.3`, but if you actually try to run against node 4, you get:

```
/Users/ian/src/irexchange/hammertime/src/asgs.js:8
  const combinedAsgs = [...allAsgs, ...data.AutoScalingGroups];
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ian/src/irexchange/hammertime/hammertime.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by ramesius** [comment]
Ahh. Yeah I believe the runtime should specify `nodejs6.10`
